roots = ["^Main.main$"]
type-class-roots = true
hie_directory = ".hiefiles"
root-modules = [
  "src/Data/Effectful/Wreq.hs",
  "src/Data/Effectful/LLM.hs",
  "src/System/Tracing.hs",
]
unused-types = true
